rpm: retry installing packages if mirrors are temporarily unreachable
ceph/teuthology pull request #1571
Opened 2020-10-23 04:21 UTC by lxbsz

Locally I had hit the same issue when installing packages it will fail
with repo metadata downloading and some other failures. Mostly this can
recovery later.

Fixes: https://tracker.ceph.com/issues/47852
Signed-off-by: Xiubo Li <xiubli@redhat.com>

2020-10-23 17:30 UTC, batrick requested changes

2020-10-23 17:30 UTC, batrick commented on teuthology/task/install/rpm.py
> +def _retry_if_failures_are_restorable(remote, args):
```suggestion
def _retry_if_failures_are_recoverable(remote, args):
```

2020-10-26 04:31 UTC, lxbsz commented on teuthology/task/install/rpm.py
> +def _retry_if_failures_are_restorable(remote, args):
Done, thanks.

2021-05-15 12:55 UTC, kshtsk commented
do we still want this? if not, maybe close?

2021-05-17 00:54 UTC, lxbsz commented
@batrick ping

2021-05-21 21:47 UTC, batrick approved these changes

2021-05-21 21:47 UTC, batrick commented
> do we still want this? if not, maybe close?

Yes

2021-05-21 21:47 UTC, batrick commented
@susebot run deploy

2021-05-21 22:54 UTC, kshtsk approved these changes

2021-05-21 23:44 UTC, merged