orch/run: add an extra check in quote()
ceph/teuthology pull request #1663
Opened 2021-08-02 11:02 UTC by rishabh-d-dave

Make quote() raise RuntimeError if the list of command arguments
contains an instance of class other than str and Raw.

2021-08-04 00:51 UTC, batrick requested changes

2021-08-05 09:25 UTC, rishabh-d-dave commented on teuthology/orchestra/run.py
> +                raise RuntimeError('command arguments should either be '
Ah, yes, that's better. Thanks! Fixed now.

2021-08-08 15:58 UTC, kshtsk commented
@susebot run deploy

2021-08-09 03:09 UTC, tchaikov approved these changes

2021-08-25 10:42 UTC, kshtsk commented
retest this please

2021-08-28 01:17 UTC, tchaikov commented
the test failure should be addressed by #1671

2024-07-01 23:53 UTC, kshtsk commented
Gonna close this PR as unattended... anyone still want it?

2024-07-08 11:47 UTC, closed without merging