orch/run: Added scan_unit_test_error
ceph/teuthology pull request #1681
Opened 2021-09-30 14:43 UTC by kamoltat

Currently when a unittest in RemoteProcess
fails it will throw a CommandFailure with
no information regarding which unittest
failed.

This PR will enable the CommandFailure to scan
for unittest failures in teuthology.log
and output them to paddles.

Currently only supports these unittests:
- gtest c++
- python nose

Signed-off-by: Kamoltat Sirivadhna <ksirivad@redhat.com>

2021-12-08 17:33 UTC, kamoltat commented
https://pulpito.ceph.com/ksirivad-2021-12-01_22:29:48-rgw:sts-wip-skoduri-dbstore-mp-distro-basic-smithi/

2021-12-08 23:10 UTC, zmc requested changes
I really like the idea of this feature, but I'm concerned about the implementation; teuthology logfiles can get into the multi-gigabyte range, and as-is this would cause each line to be evaluated against two regexes each time any command fails to execute, even if the caller catches the exception.

An easy way to mitigate this would be to make the feature opt-in. This could be done by adding a flag to `run()` that controls whether to scan after a given command fails. It could also be done by creating a helper function specifically for running unit tests that runs the tests, catches any `CommandFailedError`, and in the case of a unit-test failure raises its _own_ unit-test-specific exception.

A niche advantage to the second approach is that a helper could remember the last line it scanned each time it sees an exception, and avoid having to re-scan lines on subsequent exceptions.

2022-01-10 12:23 UTC, kshtsk commented
Parsing logs during core exception handling is in general not a good idea. Especially if we do that for any failed command, even if we know that we are not running unittest and we expect the command to be failed. If you really want to parse logs from unittest running remotely, it is better to do with separate utility wrapper runner and the decision should be taken on the caller side.
As an idea, for example, maybe there can be a parsers class for each unittest type, and there can be a list of parsers passed to the run method as a parameter to check the stream.

2022-01-10 12:24 UTC, kshtsk requested changes
See the comment above.

2022-07-06 15:32 UTC, kamoltat commented
Work being done in https://github.com/ceph/teuthology/pull/1768 instead

2022-07-06 15:32 UTC, closed without merging