suite: Do not send emails with --dry-run at schedule_fail
ceph/teuthology pull request #1778
Opened 2022-07-13 08:31 UTC by VallariAg

Do not send emails with `--dry-run` on schedule failures. 

Signed-off-by: Vallari Agrawal <val.agl002@gmail.com>

2022-07-13 15:43 UTC, kamoltat commented
Overall looks good, just need to add a unit test.

2022-07-18 14:27 UTC, kamoltat requested changes

2022-07-18 14:50 UTC, VallariAg commented on teuthology/suite/util.py
> +def schedule_fail(message, name='', dry_run=None):
Yep, working on it! :+1:

2022-07-19 20:27 UTC, kamoltat requested changes
Great job with implementing the unit test and making use of existing code to your advantage. Just left some comments for you to make a few changes, after that this should be good.

2022-07-19 20:27 UTC, kamoltat commented on teuthology/suite/test/test_init.py
> +        assert str(exc.value) == "Scheduling failed: Must specify a machine_type"
As well as unit testing these specific exceptions and making sure that the exception output is correct. We also want to make sure that with `--dry-run`, the function `util.schedule_fail()`
is not hitting `smtp.sendmail()` in `util.schedule_fail()`. We can do this by importing `teuthology.suite.util.schedule_fail`, patching it, and add something like `assert m_schedule_fail.smtp.sendmail.called == False`. You might have to mock more stuff but this should get you started.

2022-07-19 20:27 UTC, kamoltat commented on teuthology/suite/test/test_run_.py
> +
same thing here

2022-07-19 20:27 UTC, kamoltat commented on teuthology/suite/test/test_util.py
> +Branch 'no-branch' not found in repo: https://github.com/ceph/ceph-ci.git!"
same thing here, but might not have to mock as much stuff.

2022-07-21 15:38 UTC, kamoltat commented
Saw your new push, looks good! I should have addressed this in my last comment but I think we also want a unit-test case where ``--dry-run`` is not present in the command and we are expecting to hit ``smtp.sendmail``.  I know it's tedious but a good unit test makes the code more bullet-proof 😊

2022-07-21 16:17 UTC, VallariAg commented
> Saw your new push, looks good! I should have addressed this in my last comment but I think we also want a unit-test case where --dry-run is not present in the command and we are expecting to hit smtp.sendmail. I know it's tedious but a good unit test makes the code more bullet-proof 

Sounds good! I'll add that as well!

2022-07-22 19:56 UTC, kamoltat commented
@VallariAg

I grep -nr "schedule_fail" and I found that:

you're missing ``dry_run=self.args.dry_run`` in: https://github.com/ceph/teuthology/blob/526dc3720490f71840421e83bcfad1d9f4defae8/teuthology/suite/run.py#L649

2022-07-23 17:29 UTC, VallariAg commented
> I grep -nr "schedule_fail" and I found that: 
> you're missing `dry_run=self.args.dry_run` in

My bad, added the parameter now!

2022-07-25 14:29 UTC, kamoltat approved these changes
LGTM

2022-07-25 14:30 UTC, merged