teuthology: Add support for seek and sync in write_file
ceph/teuthology pull request #2010
Opened 2024-10-25 17:09 UTC by chrisphoffman

Add support for seek and sync in write_file.

This patch will allow for partial writes and sync on completion of write.

2024-11-13 22:17 UTC, kshtsk commented on teuthology/misc.py
> +    remote.write_file(path, data, bs=bs, offset=offset, sync=sync)
This method is left for backwards compatibility, for newer code, please, use only remote context function, so I mean, please, don't change this method.

2024-11-13 22:17 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param bs:      block size
Please, add info about default value.

2024-11-13 22:18 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param offset:  number of bytes to seek to in file
Add information about defaults.

2024-11-13 22:18 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param sync:    sync file
Add default value description.

2024-11-13 22:20 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param bs:      block size
Also give user more idea about what is the block size how it can be used. Probably this will require add some description above.

2024-11-13 22:21 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param sync:    sync file
Yeah... here is another point to elaborate, so user understand how to use _sync_ argument.

2024-11-13 22:22 UTC, kshtsk commented
Interesting idea, I would suggest to address the comments and maybe add unit tests.

2024-11-13 22:25 UTC, kshtsk requested changes
Interesting idea, I would suggest to address the comments and maybe add unit tests.

2024-11-18 15:43 UTC, chrisphoffman commented
> Interesting idea, I would suggest to address the comments and maybe add unit tests.

Thanks for the review. Comments addressed and tests added. PTAL

2024-11-20 09:51 UTC, kshtsk commented on teuthology/orchestra/test/test_cluster.py
> +        m_write_file.assert_called_with("filename", "content", sync=True)
Those are test not for the `remote.write_file` but for `cluster.remote_write`, I guess there should be new tests added to `test/test_remote.py` module instead.

2024-11-20 10:31 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +        :param bs:      write up to N bytes at a time, defaults 512
I guess default is None, maybe just give a reference to `dd`, just add another line right after `Write data to remote file` above, like:

```The data written in 512-byte blocks, provide `bs` to use bigger blocks.```

2024-11-20 10:34 UTC, kshtsk commented on teuthology/orchestra/remote.py
> +            args += ' conv=sync'
I don't remember exactly if the `conv` can be used multiple times in dd, if not we must take into consideration `notrunct` when `append` needed. Btw, one of use case for a unit test.

2025-01-06 16:00 UTC, chrisphoffman commented on teuthology/orchestra/test/test_cluster.py
> +        m_write_file.assert_called_with("filename", "content", sync=True)
Done.

2025-01-06 16:00 UTC, chrisphoffman commented on teuthology/orchestra/cluster.py
> +                   **kwargs):
No need for cluster wide call at this time.

2025-01-07 11:46 UTC, kshtsk approved these changes

2025-01-07 13:22 UTC, merged